version: '3'
services:
    jupyter:
        build: docker/jupyter
        ports:
            - 8888:8888
        volumes:
            - .:/home/jovyan
    this_redis:
       image: redis
       volumes:
           - redis_data:/data
    postgres:
        build: docker/postgres 
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
    redis_data:
